name: curso django
on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    ###instalando dependencias###
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync -d

    ###Flake8###
    - name: flake8
      uses: py-actions/flake8@v2

    ###Pytest###
    - name: Pytests
      run: |
        pipenv install --dev
        pipenv run pytest --cov=pypro

    ###Code-cov###
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)