name: curso django
on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    ###instalando dependencias###
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync -d

    ###Flake8###
    - name: flake8
      uses: py-actions/flake8@v2

    ###Pytest###
    - name: Pytests
      run: |
        pipenv install --dev
        pipenv run pytest --cov=pypro

    - name: CodeCov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov

        chmod +x codecov
        ./codecov